[2022-03-28 21:23:28,874] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-28T21:23:27.894948+00:00 [queued]>
[2022-03-28 21:23:28,883] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-28T21:23:27.894948+00:00 [queued]>
[2022-03-28 21:23:28,883] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-28 21:23:28,883] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-28 21:23:28,884] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-28 21:23:28,901] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-03-28 21:23:27.894948+00:00
[2022-03-28 21:23:28,905] {standard_task_runner.py:52} INFO - Started process 325 to run task
[2022-03-28 21:23:28,907] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-03-28T21:23:27.894948+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmp149zvlq_', '--error-file', '/tmp/tmpm99qrv5p']
[2022-03-28 21:23:28,908] {standard_task_runner.py:77} INFO - Job 72: Subtask load_seed_data_once
[2022-03-28 21:23:28,958] {logging_mixin.py:109} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-28T21:23:27.894948+00:00 [running]> on host 713dce2392ed
[2022-03-28 21:23:29,051] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-03-28T21:23:27.894948+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-28T21:23:27.894948+00:00
[2022-03-28 21:23:29,051] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-28 21:23:29,052] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-03-28 21:23:29,061] {subprocess.py:85} INFO - Output:
[2022-03-28 21:23:32,507] {subprocess.py:89} INFO - Running with dbt=0.20.0
[2022-03-28 21:23:35,777] {subprocess.py:89} INFO - Found 5 models, 0 tests, 0 snapshots, 0 analyses, 338 macros, 0 operations, 3 seed files, 0 sources, 0 exposures
[2022-03-28 21:23:35,778] {subprocess.py:89} INFO - 
[2022-03-28 21:23:37,678] {subprocess.py:89} INFO - 21:23:37 | Concurrency: 200 threads (target='dev')
[2022-03-28 21:23:37,679] {subprocess.py:89} INFO - 21:23:37 |
[2022-03-28 21:23:37,697] {subprocess.py:89} INFO - 21:23:37 | 1 of 3 START seed file public.bookings_1............................. [RUN]
[2022-03-28 21:23:37,697] {subprocess.py:89} INFO - 21:23:37 | 2 of 3 START seed file public.bookings_2............................. [RUN]
[2022-03-28 21:23:37,698] {subprocess.py:89} INFO - 21:23:37 | 3 of 3 START seed file public.customers.............................. [RUN]
[2022-03-28 21:23:38,703] {subprocess.py:89} INFO - * Deprecation Warning: The quote_columns parameter was not set for seeds, so the
[2022-03-28 21:23:38,703] {subprocess.py:89} INFO - default value of False was chosen. The default will change to True in a future
[2022-03-28 21:23:38,703] {subprocess.py:89} INFO - release.
[2022-03-28 21:23:38,703] {subprocess.py:89} INFO - 
[2022-03-28 21:23:38,703] {subprocess.py:89} INFO - For more information, see:
[2022-03-28 21:23:38,703] {subprocess.py:89} INFO - https://docs.getdbt.com/v0.15/docs/seeds#section-specify-column-quoting
[2022-03-28 21:23:39,677] {subprocess.py:89} INFO - 21:23:39 | 3 of 3 OK loaded seed file public.customers.......................... [[32mINSERT 2[0m in 1.98s]
[2022-03-28 21:23:39,703] {subprocess.py:89} INFO - 21:23:39 | 1 of 3 OK loaded seed file public.bookings_1......................... [[32mINSERT 7[0m in 2.01s]
[2022-03-28 21:23:39,792] {subprocess.py:89} INFO - 21:23:39 | 2 of 3 OK loaded seed file public.bookings_2......................... [[32mINSERT 7[0m in 2.09s]
[2022-03-28 21:23:40,335] {subprocess.py:89} INFO - 21:23:40 |
[2022-03-28 21:23:40,335] {subprocess.py:89} INFO - 21:23:40 | Finished running 3 seeds in 4.56s.
[2022-03-28 21:23:40,348] {subprocess.py:89} INFO - 
[2022-03-28 21:23:40,348] {subprocess.py:89} INFO - [32mCompleted successfully[0m
[2022-03-28 21:23:40,348] {subprocess.py:89} INFO - 
[2022-03-28 21:23:40,348] {subprocess.py:89} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-03-28 21:23:41,503] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-28 21:23:41,529] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220328T212327, start_date=20220328T212328, end_date=20220328T212341
[2022-03-28 21:23:41,548] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-28 21:23:41,575] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
