[2022-03-13 22:07:42,345] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-13T22:07:41.584650+00:00 [queued]>
[2022-03-13 22:07:42,357] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-13T22:07:41.584650+00:00 [queued]>
[2022-03-13 22:07:42,357] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-13 22:07:42,357] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-13 22:07:42,358] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-13 22:07:42,376] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-03-13 22:07:41.584650+00:00
[2022-03-13 22:07:42,382] {standard_task_runner.py:52} INFO - Started process 130 to run task
[2022-03-13 22:07:42,392] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-03-13T22:07:41.584650+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpro3ocfmh', '--error-file', '/tmp/tmpoezroiav']
[2022-03-13 22:07:42,392] {standard_task_runner.py:77} INFO - Job 42: Subtask load_seed_data_once
[2022-03-13 22:07:42,440] {logging_mixin.py:109} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-13T22:07:41.584650+00:00 [running]> on host e176062f3fa2
[2022-03-13 22:07:42,549] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-03-13T22:07:41.584650+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-13T22:07:41.584650+00:00
[2022-03-13 22:07:42,550] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-13 22:07:42,550] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-03-13 22:07:42,561] {subprocess.py:85} INFO - Output:
[2022-03-13 22:07:45,409] {subprocess.py:89} INFO - Running with dbt=0.20.0
[2022-03-13 22:07:48,911] {subprocess.py:89} INFO - Found 5 models, 0 tests, 0 snapshots, 0 analyses, 338 macros, 0 operations, 3 seed files, 0 sources, 0 exposures
[2022-03-13 22:07:48,912] {subprocess.py:89} INFO - 
[2022-03-13 22:07:51,989] {subprocess.py:89} INFO - 22:07:51 | Concurrency: 200 threads (target='dev')
[2022-03-13 22:07:51,990] {subprocess.py:89} INFO - 22:07:51 |
[2022-03-13 22:07:52,008] {subprocess.py:89} INFO - 22:07:52 | 1 of 3 START seed file public.bookings_1............................. [RUN]
[2022-03-13 22:07:52,009] {subprocess.py:89} INFO - 22:07:52 | 2 of 3 START seed file public.bookings_2............................. [RUN]
[2022-03-13 22:07:52,009] {subprocess.py:89} INFO - 22:07:52 | 3 of 3 START seed file public.customers.............................. [RUN]
[2022-03-13 22:07:52,812] {subprocess.py:89} INFO - * Deprecation Warning: The quote_columns parameter was not set for seeds, so the
[2022-03-13 22:07:52,813] {subprocess.py:89} INFO - default value of False was chosen. The default will change to True in a future
[2022-03-13 22:07:52,813] {subprocess.py:89} INFO - release.
[2022-03-13 22:07:52,813] {subprocess.py:89} INFO - 
[2022-03-13 22:07:52,813] {subprocess.py:89} INFO - For more information, see:
[2022-03-13 22:07:52,813] {subprocess.py:89} INFO - https://docs.getdbt.com/v0.15/docs/seeds#section-specify-column-quoting
[2022-03-13 22:07:52,816] {subprocess.py:89} INFO - * Deprecation Warning: The quote_columns parameter was not set for seeds, so the
[2022-03-13 22:07:52,816] {subprocess.py:89} INFO - default value of False was chosen. The default will change to True in a future
[2022-03-13 22:07:52,816] {subprocess.py:89} INFO - release.
[2022-03-13 22:07:52,816] {subprocess.py:89} INFO - 
[2022-03-13 22:07:52,816] {subprocess.py:89} INFO - For more information, see:
[2022-03-13 22:07:52,817] {subprocess.py:89} INFO - https://docs.getdbt.com/v0.15/docs/seeds#section-specify-column-quoting
[2022-03-13 22:07:54,177] {subprocess.py:89} INFO - 22:07:54 | 2 of 3 OK loaded seed file public.bookings_2......................... [[32mINSERT 7[0m in 2.17s]
[2022-03-13 22:07:54,199] {subprocess.py:89} INFO - 22:07:54 | 3 of 3 OK loaded seed file public.customers.......................... [[32mINSERT 2[0m in 2.19s]
[2022-03-13 22:07:54,336] {subprocess.py:89} INFO - 22:07:54 | 1 of 3 OK loaded seed file public.bookings_1......................... [[32mINSERT 7[0m in 2.33s]
[2022-03-13 22:07:54,963] {subprocess.py:89} INFO - 22:07:54 |
[2022-03-13 22:07:54,963] {subprocess.py:89} INFO - 22:07:54 | Finished running 3 seeds in 6.05s.
[2022-03-13 22:07:54,976] {subprocess.py:89} INFO - 
[2022-03-13 22:07:54,976] {subprocess.py:89} INFO - [32mCompleted successfully[0m
[2022-03-13 22:07:54,976] {subprocess.py:89} INFO - 
[2022-03-13 22:07:54,976] {subprocess.py:89} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-03-13 22:07:56,211] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-13 22:07:56,271] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220313T220741, start_date=20220313T220742, end_date=20220313T220756
[2022-03-13 22:07:56,310] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-13 22:07:56,346] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
